<?php

/**
 * See LICENSE.md file for further details.
 */

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;
use MagicSunday\Webtrees\PedigreeChart\Configuration;

/** @var Configuration $configuration */
/** @var string $title */
/** @var string $moduleName */
/** @var Individual $individual */
/** @var Tree $tree */
/** @var array $chartParams */
/** @var string $javascript */
/** @var string $stylesheet */
/** @var string $svgStylesheet */
/** @var string $ajaxUrl */
?>

<div id="page-pedigree">
    <h2 class="wt-page-title"><?= $title ?></h2>

    <form id="webtrees-pedigree-chart-form" method="post" class="wt-page-options wt-page-options-pedigree-chart d-print-none">
        <?= csrf_field() ?>

        <div class="form-group row">
            <label class="col-sm-3 col-form-label wt-page-options-label" for="xref">
                <?= I18N::translate('Individual') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <?=
                    view('components/select-individual', [
                        'id'         => 'xref',
                        'name'       => 'xref',
                        'individual' => $individual,
                        'tree'       => $tree,
                        'required'   => true,
                    ])
                ?>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-3 col-form-label wt-page-options-label" for="generations">
                <?= I18N::translate('Generations') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <?=
                    view('components/select', [
                        'id'       => 'generations',
                        'name'     => 'generations',
                        'selected' => $configuration->getGenerations(),
                        'options'  => $configuration->getGenerationsList(),
                        'class'    => 'form-control-sm',
                    ])
                ?>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-form-label col-sm-3 wt-page-options-label">
                <?= I18N::translate('Layout') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <?=
                    view('components/checkbox', [
                        'id'      => 'showEmptyBoxes',
                        'name'    => 'showEmptyBoxes',
                        'label'   => I18N::translate('Show empty boxes for missing individuals. Caution: May slow down your system!'),
                        'checked' => $configuration->getShowEmptyBoxes(),
                    ])
                ?>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-12 wt-page-options-value text-center">
                <div class="btn-toolbar justify-content-between">
                    <div class="btn-group btn-group-sm">
                        <input class="btn btn-primary" type="submit" value="<?= I18N::translate('view') ?>">
                    </div>

                    <div class="justify-content-around">
                        <div class="btn-group btn-group-sm mr-2">
                            <button class="btn btn-secondary" type="button" id="centerButton">
                                <?= I18N::translate('Re center') ?>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <div class="row">
        <div id="webtrees-pedigree-chart-container" class="wt-ajax-load wt-page-content wt-chart wt-pedigree-chart"></div>
    </div>
</div>

<?php View::push('styles') ?>
<link rel="stylesheet" href="<?= e($stylesheet) ?>">
<link rel="stylesheet" href="<?= e($svgStylesheet) ?>">
<?php View::endpush(); ?>

<?php View::push('javascript'); ?>
<script src="<?= e($javascript) ?>"></script>
<script>

/**
 * Returns the AJAX update URL.
 *
 * @param {PedigreeChart} pedigreeChart
 * @param {string}        baseUrl
 *
 * @returns {string}
 */
function getUrl(pedigreeChart, baseUrl)
{
    let url = new URL(baseUrl);
    url.searchParams.set("xref", document.getElementById('xref').value);
    url.searchParams.set("generations", pedigreeChart.configuration.generations);

    return url.toString();
}

/**
 * Load chart data and draws the chart.
 *
 * @param {PedigreeChart} pedigreeChart
 * @param {string}        dataUrl
 */
function drawChart(pedigreeChart, dataUrl)
{
    $.getJSON(
        getUrl(pedigreeChart, dataUrl),
        function (data) {
            pedigreeChart.draw(data);

            // document.getElementById("webtrees-pedigree-chart-container")
            //     .scrollIntoView(true);
        }
    );
}

// Wait for DOM to be ready
document.addEventListener("DOMContentLoaded", function () {
    // Set up storage object
    let storage = new WebtreesPedigreeChart.Storage("webtrees-fan-chart");

    // Register all form elements valid for storing data
    storage.register("generations");
    storage.register("showEmptyBoxes");

    let data    = <?= $chartParams ?>;
    let ajaxUrl = <?= json_encode($ajaxUrl) ?>;
    let cssUrl  = <?= json_encode($svgStylesheet) ?>;

    // Create chart instance with stored configuration
    const pedigreeChart = new WebtreesPedigreeChart.PedigreeChart(
        "#webtrees-pedigree-chart-container",
        {
            labels         : data.labels,
            generations    : parseInt(storage.read("generations")),
            defaultColor   : data.defaultColor,
            fontColor      : data.fontColor,
            showEmptyBoxes : storage.read("showEmptyBoxes"),
            rtl            : data.rtl
        }
    );

    pedigreeChart.cssFile = cssUrl;

    // Load initial chart data
    drawChart(pedigreeChart, ajaxUrl);

    // Redraw chart upon form submit
    document.getElementById('webtrees-pedigree-chart-form').addEventListener('submit', function (event) {
        event.preventDefault();

        // Update configuration with changed form values
        pedigreeChart.configuration.generations    = parseInt(document.getElementById('generations').value);
        pedigreeChart.configuration.showEmptyBoxes = !!document.getElementById('showEmptyBoxes').checked;

        drawChart(pedigreeChart, ajaxUrl);
    });
});

</script>
<?php View::endpush(); ?>
