<?php
declare(strict_types=1);

/**
 * See LICENSE.md file for further details.
 */
use Fisharebest\Webtrees\Bootstrap4;
use Fisharebest\Webtrees\Functions\FunctionsEdit;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;
use MagicSunday\Webtrees\PedigreeChartModule;

?>

<div id="page-pedigree">
    <h2 class="wt-page-title"><?= $title ?></h2>

    <form class="wt-page-options wt-page-options-pedigree-chart d-print-none">
        <input type="hidden" name="route" value="module">
        <input type="hidden" name="module" value="webtrees-pedigree-chart">
        <input type="hidden" name="ged" value="<?= e($tree->getName()) ?>">
        <input type="hidden" name="action" value="PedigreeChart">

        <fieldset class="form-group">
            <div class="row">
                <label class="col-sm-3 col-form-label wt-page-options-label" for="xref">
                    <?= I18N::translate('Individual') ?>
                </label>
                <div class="col-sm-9 wt-page-options-value">
                    <?= FunctionsEdit::formControlIndividual($tree, $individual, ['id' => 'xref', 'name' => 'xref']) ?>
                </div>
            </div>
        </fieldset>

        <fieldset class="form-group">
            <div class="row">
                <label class="col-sm-3 col-form-label wt-page-options-label" for="generations">
                    <?= I18N::translate('Generations'); ?>
                </label>
                <div class="col-sm-9 wt-page-options-value">
                    <?=
                        Bootstrap4::select(
                            FunctionsEdit::numericOptions(range(PedigreeChartModule::MIN_GENERATIONS, PedigreeChartModule::MAX_GENERATIONS)),
                            $generations,
                            [
                                'id'   => 'generations',
                                'name' => 'generations',
                            ]
                        );
                    ?>
                </div>
            </div>
        </fieldset>

        <fieldset class="form-group">
            <div class="row">
                <div class="col-sm-3 wt-page-options-label"></div>
                <div class="col-sm-9 wt-page-options-value">
                    <input class="btn btn-primary" type="submit" value="<?= I18N::translate('view') ?>">
                    <input class="btn btn-primary" type="reset" value="<?= I18N::translate('reset') ?>" id="resetButton">
                </div>
            </div>
        </fieldset>
    </form>

    <div class="row">
        <div id="pedigree_chart" class="wt-ajax-load wt-page-content wt-chart wt-pedigree-chart"></div>
    </div>
</div>

<?php View::push('styles') ?>

<link rel="stylesheet" type="text/css" href="modules_v3/webtrees-pedigree-chart/css/pedigree-chart.css">

<?php View::endpush(); ?>

<?php View::push('javascript'); ?>

<script type="text/javascript" src="modules_v3/webtrees-pedigree-chart/js/pedigree-chart.js"></script>
<script type="text/javascript">

function PedigreeChart(data)
{
    rso.options = new rso.Options(
        data.individualUrl,
        data.labels,
        data.generations,
        data.defaultColor,
        data.fontColor,
        data.rtl
    );

// console.log(rso.options);

    rso.options = Object.assign({}, rso.options, data);

    rso.initChart(rso.options.data);
    // rso.initData(rso.options.data);
    // rso.createArcElements();
    // rso.updateViewBox();
}

new PedigreeChart(<?= $chartParams ?>);

</script>

<?php View::endpush(); ?>
