<?php

/**
 * This file is part of the package magicsunday/webtrees-pedigree-chart.
 *
 * For the full copyright and license information, please read the
 * LICENSE file distributed with this source code.
 */

declare(strict_types=1);

use Fisharebest\Webtrees\View;
use MagicSunday\Webtrees\PedigreeChart\Configuration;

/**
 * @var string        $javascript
 * @var Configuration $configuration
 * @var array         $id                The unique chart ID
 * @var array         $chartParams
 * @var string[]      $exportStylesheets A list of stylesheets used by SVG export
 * @var array         $data              The chart data
 */
?>

<div class="webtrees-pedigree-chart-container" id="webtrees-pedigree-chart-container-<?php echo $id; ?>"></div>

<?php View::push('javascript'); ?>
<script type="module">

import(<?php echo json_encode($javascript); ?>).then(({ PedigreeChart }) => {
    const opts = (typeof WebtreesPedigreeChart !== "undefined" && WebtreesPedigreeChart.chartOptions) || {};

    new PedigreeChart(
        "#webtrees-pedigree-chart-container-<?php echo $id; ?>",
        {
            labels: <?php echo json_encode($chartParams['labels']); ?>,
            rtl: <?php echo json_encode($chartParams['rtl']); ?>,
            cssFiles: <?php echo json_encode($exportStylesheets); ?>,

            get generations() {
                return opts.generations ?? <?php echo $configuration->getGenerations(); ?>;
            },

            get treeLayout() {
                return opts.treeLayout ?? <?php echo json_encode($configuration->getLayout()); ?>;
            },

            get openNewTabOnClick() {
                return opts.openNewTabOnClick ?? <?php echo json_encode($configuration->getOpenNewTabOnClick()); ?>;
            },

            get showAlternativeName() {
                return opts.showAlternativeName ?? <?php echo json_encode($configuration->getShowAlternativeName()); ?>;
            },

            get showFamilyColors() {
                return opts.showFamilyColors ?? <?php echo json_encode($configuration->getShowFamilyColors()); ?>;
            },

            get paternalColor() {
                return opts.paternalColor ?? <?php echo json_encode($configuration->getPaternalColor()); ?>;
            },

            get maternalColor() {
                return opts.maternalColor ?? <?php echo json_encode($configuration->getMaternalColor()); ?>;
            },

            nameAbbreviation: <?php echo json_encode($chartParams['nameAbbreviation']); ?>,

            data: <?php echo json_encode($data); ?>
        }
    );
});

</script>
<?php View::endpush(); ?>
