<?php

/**
 * This file is part of the package magicsunday/webtrees-pedigree-chart.
 *
 * For the full copyright and license information, please read the
 * LICENSE file distributed with this source code.
 */

declare(strict_types=1);

use Fisharebest\Webtrees\View;
use MagicSunday\Webtrees\PedigreeChart\Configuration;

/**
 * @var string        $javascript
 * @var Configuration $configuration
 * @var array         $id                The unique chart ID
 * @var array         $chartParams
 * @var string[]      $exportStylesheets A list of stylesheets used by SVG export
 * @var array         $data              The chart data
 */
?>

<div class="webtrees-pedigree-chart-container" id="webtrees-pedigree-chart-container-<?php echo $id; ?>"></div>

<?php View::push('javascript'); ?>
<script type="module">

import(<?php echo json_encode($javascript); ?>).then(({ PedigreeChart }) => {
    new PedigreeChart(
        "#webtrees-pedigree-chart-container-<?php echo $id; ?>",
        {
            labels: <?php echo json_encode($chartParams['labels']); ?>,
            rtl: <?php echo json_encode($chartParams['rtl']); ?>,
            cssFiles: <?php echo json_encode($exportStylesheets); ?>,

            get generations() {
                return (typeof generations !== "undefined" && generations !== null) ? generations : <?php echo $configuration->getGenerations(); ?>
            },

            get treeLayout() {
                return (typeof treeLayout !== "undefined" && treeLayout !== null) ? treeLayout : <?php echo json_encode($configuration->getLayout()); ?>;
            },

            get openNewTabOnClick() {
                return (typeof openNewTabOnClick !== "undefined" && openNewTabOnClick !== null) ? openNewTabOnClick : <?php echo json_encode($configuration->getOpenNewTabOnClick()); ?>;
            },

            get showAlternativeName() {
                return (typeof showAlternativeName !== "undefined" && showAlternativeName !== null) ? showAlternativeName : <?php echo json_encode($configuration->getShowAlternativeName()); ?>;
            },

            get showFamilyColors() {
                return (typeof showFamilyColors !== "undefined" && showFamilyColors !== null) ? showFamilyColors : <?php echo json_encode($configuration->getShowFamilyColors()); ?>;
            },

            get paternalColor() {
                return (typeof paternalColor !== "undefined" && paternalColor !== null) ? paternalColor : <?php echo json_encode($configuration->getPaternalColor()); ?>;
            },

            get maternalColor() {
                return (typeof maternalColor !== "undefined" && maternalColor !== null) ? maternalColor : <?php echo json_encode($configuration->getMaternalColor()); ?>;
            },

            nameAbbreviation: <?php echo json_encode($chartParams['nameAbbreviation']); ?>,

            data: <?php echo json_encode($data); ?>
        }
    );
});

</script>
<?php View::endpush(); ?>
