<?php

/**
 * See LICENSE.md file for further details.
 */

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;
use MagicSunday\Webtrees\PedigreeChart\Configuration;

/**
 * @var Configuration $configuration
 * @var string        $title
 * @var string        $moduleName
 * @var Individual    $individual
 * @var Tree          $tree
 * @var array         $chartParams
 * @var string        $javascript
 * @var string        $stylesheet
 * @var string        $svgStylesheet
 * @var string        $ajaxUrl
 */
?>

<div id="page-pedigree">
    <h2 class="wt-page-title"><?= $title ?></h2>

    <form id="webtrees-pedigree-chart-form" method="post" class="wt-page-options wt-page-options-pedigree-chart d-print-none">
        <?= csrf_field() ?>

        <div class="form-group row">
            <label class="col-sm-3 col-form-label wt-page-options-label" for="xref">
                <?= I18N::translate('Individual') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <?=
                    view('components/select-individual', [
                        'id'         => 'xref',
                        'name'       => 'xref',
                        'individual' => $individual,
                        'tree'       => $tree,
                        'required'   => true,
                    ])
                ?>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-3 col-form-label wt-page-options-label" for="generations">
                <?= I18N::translate('Generations') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <?=
                    view('components/select', [
                        'id'       => 'generations',
                        'name'     => 'generations',
                        'selected' => $configuration->getGenerations(),
                        'options'  => $configuration->getGenerationsList(),
                        'class'    => 'form-control-sm',
                    ])
                ?>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-form-label col-sm-3 wt-page-options-label">
                <?= I18N::translate('Orientation') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value" id="layout">
                <?=
                    view('components/radios-inline', [
                        'name' => 'layout',
                        'options' => [
                            Configuration::LAYOUT_RIGHTLEFT => view('icons/pedigree-left') . I18N::translate('left'),
                            Configuration::LAYOUT_LEFTRIGHT => view('icons/pedigree-right') . I18N::translate('right'),
                            Configuration::LAYOUT_BOTTOMTOP => view('icons/pedigree-up') . I18N::translate('up'),
                            Configuration::LAYOUT_TOPBOTTOM => view('icons/pedigree-down') . I18N::translate('down'),
                        ],
                        'selected' => $configuration->getLayout(),
                    ])
                ?>
            </div>
        </div>

        <div class="collapse" id="showMoreOptions">
            <div class="form-group row">
                <label class="col-form-label col-sm-3 wt-page-options-label">
                    <?= I18N::translate('Layout') ?>
                </label>
                <div class="col-sm-9 wt-page-options-value">
                    <?=
                    view('components/checkbox', [
                        'id'      => 'showEmptyBoxes',
                        'name'    => 'showEmptyBoxes',
                        'label'   => I18N::translate('Show empty boxes for missing individuals. Caution: May slow down your system!'),
                        'checked' => $configuration->getShowEmptyBoxes(),
                    ])
                    ?>
                </div>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-12 wt-page-options-value text-center">
                <div class="btn-toolbar justify-content-between">
                    <div class="btn-group btn-group-sm">
                        <button id="options"
                                class="btn btn-primary"
                                type="button"
                                data-bs-toggle="collapse"
                                data-bs-target="#showMoreOptions"
                                aria-expanded="false"
                                aria-controls="showMoreOptions">
                            <span><?= I18N::translate('Show more options') ?></span>
                            <span class="d-none"><?= I18N::translate('Hide more options') ?></span>
                        </button>
                    </div>

                    <div class="btn-group btn-group-sm">
                        <input class="btn btn-primary" type="submit" value="<?= I18N::translate('view') ?>">
                    </div>

                    <div class="justify-content-around">
                        <div class="btn-group btn-group-sm mr-2">
                            <button class="btn btn-secondary" type="button" id="centerButton">
                                <?= I18N::translate('Re center') ?>
                            </button>
                        </div>
                        <div class="btn-group btn-group-sm">
                            <button class="btn btn-secondary border-right" type="button" id="exportPNG">
                                <?= I18N::translate('Export as PNG') ?>
                            </button>
                            <button class="btn btn-secondary border-left" type="button" id="exportSVG">
                                <?= I18N::translate('Export as SVG') ?>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <div id="pedigree-chart-url" class="row wt-ajax-load wt-page-content wt-chart wt-pedigree-chart"></div>
</div>

<?php View::push('styles') ?>
<link rel="stylesheet" href="<?= e($stylesheet) ?>">
<link rel="stylesheet" href="<?= e($svgStylesheet) ?>">
<?php View::endpush(); ?>

<?php View::push('javascript'); ?>
<script src="<?= e($javascript) ?>"></script>
<script>

/**
 * Returns the AJAX update URL.
 *
 * @param {String} baseUrl
 * @param {String} generations
 *
 * @returns {String}
 */
function getUrl(baseUrl, generations)
{
    let url = new URL(baseUrl);
    url.searchParams.set("xref", document.getElementById('xref').value);
    url.searchParams.set("generations", generations);

    return url.toString();
}

/**
 * Set visibility of "Show more options" to previous state after page reload.
 * Toggle text on "Show more options" on click.
 *
 * @param {Storage} storage
 */
function toggleMoreOptions(storage)
{
    // Options container
    const showMoreOptions = document.getElementById('showMoreOptions');

    // Options toggle button
    const optionsToggle = document.getElementById('options');

    showMoreOptions.addEventListener('shown.bs.collapse', () => {
        storage.write("showMoreOptions", true);
    });

    showMoreOptions.addEventListener('hidden.bs.collapse', () => {
        storage.write("showMoreOptions", false);
    });

    optionsToggle.addEventListener('click', () => {
      Array.from(optionsToggle.children).forEach((element, index) => {
        element.classList.toggle('d-none');
      });
    });

    if (storage.read("showMoreOptions")) {
      optionsToggle.click()
    }
}

// Set up storage object
const storage = new WebtreesPedigreeChart.Storage("webtrees-pedigree-chart");

// Register all form elements valid for storing data
storage.register("generations");
storage.register("showEmptyBoxes");
storage.register("layout");

// Handle option toggle button
toggleMoreOptions(storage);

// Set initial stored value for radio button group
let formElements = document.getElementById("webtrees-pedigree-chart-form").elements;
formElements.namedItem("layout").value = storage.read("layout");

const generations    = parseInt(storage.read("generations"));
const showEmptyBoxes = storage.read("showEmptyBoxes");
const treeLayout     = storage.read("layout");
const ajaxUrl        = getUrl(<?= json_encode($ajaxUrl) ?>, storage.read("generations"))

document.getElementById("pedigree-chart-url")
    .setAttribute('data-wt-ajax-url', ajaxUrl);

</script>
<?php View::endpush(); ?>
