<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use MagicSunday\Webtrees\PedigreeChart\Configuration;

/**
 * @var Configuration $configuration
 */

?>

<div class="form-group row">
    <label class="col-sm-3 col-form-label wt-page-options-label" for="generations">
        <?= I18N::translate('Generations') ?>
    </label>
    <div class="col-sm-9 wt-page-options-value">
        <?=
        view('components/select', [
            'id'       => 'generations',
            'name'     => 'generations',
            'selected' => $configuration->getGenerations(),
            'options'  => $configuration->getGenerationsList(),
            'class'    => 'form-control-sm',
        ])
        ?>
    </div>
</div>