<?php

/**
 * This file is part of the package magicsunday/webtrees-pedigree-chart.
 *
 * For the full copyright and license information, please read the
 * LICENSE file distributed with this source code.
 */

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use MagicSunday\Webtrees\PedigreeChart\Configuration;

/**
 * @var Configuration $configuration
 * @var string        $moduleName
 */
?>

<div class="form-group row">
    <label class="col-form-label col-sm-3 wt-page-options-label">
        <?= I18N::translate('Layout') ?>
    </label>
    <div class="col-sm-9 wt-page-options-value">
        <?=
            view($moduleName . '::modules/components/checkbox', [
                'name'      => 'showEmptyBoxes',
                'label'     => I18N::translate('Show empty boxes for missing individuals. Caution: May slow down your system!'),
                'checked'   => $configuration->getShowEmptyBoxes(),
                'unchecked' => '0',
            ])
        ?>

        <div class="mt-3">
            <?=
                view($moduleName . '::modules/components/checkbox', [
                    'name'      => 'openNewTabOnClick',
                    'label'     => I18N::translate('Open individual in new browser window/tab'),
                    'checked'   => $configuration->getOpenNewTabOnClick(),
                    'unchecked' => '0',
                ])
            ?>
            <small class="ps-4 form-text text-muted form-element-description">
                <?= I18N::translate('Open the current individual\'s detail page in a new browser window/tab when it\'s left-clicked, otherwise the current window/tab is used.') ?>
            </small>
        </div>

        <div class="mt-3">
            <?=
                view($moduleName . '::modules/components/checkbox', [
                    'name'      => 'showAlternativeName',
                    'label'     => I18N::translate('Show alternative name of individual'),
                    'checked'   => $configuration->getShowAlternativeName(),
                    'unchecked' => '0',
                ])
            ?>
            <small class="ps-4 form-text text-muted form-element-description">
                <?= I18N::translate('Displays a person\'s alternate name, if available. This simultaneously enlarges the individuals\' respective boxes to create the necessary space for the display.') ?>
            </small>
        </div>
    </div>
</div>
