<?php

/**
 * See LICENSE.md file for further details.
 */

declare(strict_types=1);

/**
 * @var string $block_id
 * @var string $chart_url
 */
?>

<style>
#webtrees-pedigree-chart-container svg {
    min-height: unset !important;
}
</style>

<div id="chart-block-<?= e($block_id) ?>"></div>

<script>
    $(<?= json_encode('#chart-block-' . $block_id) ?>).load(<?= json_encode($chart_url) ?>);
</script>
