<?php

/**
 * This file is part of the package magicsunday/webtrees-pedigree-chart.
 *
 * For the full copyright and license information, please read the
 * LICENSE file that was distributed with this source code.
 */

declare(strict_types=1);

use Fisharebest\Webtrees\View;

/**
 * @var string $content The content to output
 */
?>

<?= $content ?>

<?= View::stack('styles') ?>
<?= View::stack('javascript') ?>
